### PR TITLE
ARM64 support

### PR DESCRIPTION
**Pull request by brainstorm**
Related to PR https://github.com/openpnp/openpnp-capture-java/pull/6 and https://github.com/openpnp/openpnp/issues/916

### CODE REVIEW

**Comment by brainstorm** [comment]
All green from my side, @vonnieda, please feel free to merge this PR together with: https://github.com/openpnp/openpnp-capture-java/pull/6

**Comment by vonnieda** [comment]
@brainstorm This does not seem to have generated aarch64 binaries. See https://github.com/openpnp/openpnp-capture/suites/2762311147/artifacts/61144767. 

```
> file *
libopenpnp-capture.0.0.20.dylib: Mach-O 64-bit dynamically linked shared library x86_64
libopenpnp-capture.dylib:        Mach-O 64-bit dynamically linked shared library x86_64
libopenpnp-capture.so:           ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=a10cb9ba723ccc9b136758a5f733d521edba4277, not stripped
libopenpnp-capture.so.0.0.20:    ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=a10cb9ba723ccc9b136758a5f733d521edba4277, not stripped
[jason@Driftwood:~/Desktop/artifact]
>
```

**Comment by vonnieda** [comment]
I think you need to rename the files based on the platform and arch so they don't get overwritten, a la https://github.com/openpnp/openpnp-capture/pull/45/files#diff-6ac3f79fc25d95cd1e3d51da53a4b21b939437392578a35ae8cd6d5366ca5485L39

**Comment by vonnieda** [comment]
This also seems to not upload the test programs anymore. I'm going to revert this for now until we can get the issues fixed.

**Comment by brainstorm** [comment]
Alright, I applied the suggestins on PR #47, can you please take a peek @vonnieda ?

**Pull request merged**
